default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "password" %> 
  host: localhost

development:
  <<: *default
  database: clinicsync_development

test:
  <<: *default
  database: clinicsync_test

production:
  <<: *default
  database: clinicsync_production
