default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "password" %> 
  host: localhost

development:
  <<: *default
  database: clinicsync_development

test:
  adapter: postgresql
  encoding: unicode
  database: clinicsync_test
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

production:
  <<: *default
  database: clinicsync_production
